spring.application.name=monitoring

# Tomcat
server.port=8091

# Dev Tools
spring.devtools.restart.enabled=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.check-template-location=true

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# profile active
spring.profiles.active=local

# coolsms
#coolsms.api-key=NCS5NJ2B47BSLF3X
#coolsms.api-secret=OM3CAC3IE8C9ZG5J5HHZDYBBLCYYUGKU
#coolsms.from-number=010-8376-3942

# multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB