spring.application.name=monitoring

# Tomcat
server.port=8091

# Dev Tools
spring.devtools.restart.enabled=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.check-template-location=true

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# profile active
spring.profiles.active=local

# coolsms
coolsms.api-key=NCS84KRAW8JWLSUZ
coolsms.api-secret=AX6ZUV0ZAZA8D7WF78NOYWJRUYMWGVYA
coolsms.from-number=01083763942

# ???? ????
# ? ?? ?? ? 10000 (10?) ?? ??
scheduler.timeout-ms=10000

# multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB